# Copyright © 2025 PI & Other Tales Inc.. All Rights Reserved.
version: '3.8'

services:
  juno:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - CONFIG_PATH=/app/data/config.yaml
    ports:
      - "8000:8000"
    restart: unless-stopped